### ISSUE TITLE
Remove hardcoded data in production docker compose 

### ISSUE THREAD

**Issue by adriancast** [adriancast/django-template-new#2]
Inside the file docker-compose.prod.yml we can find that the path of the image is hardcoded with my user

We should have something like 

Also would be nice to have some docs about this

```yaml
version: '3.7'

services:
  web:
    image: ghcr.io/<user_organization>/<repository_name>/app:latest
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
```
